[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "https://irkfrlvddkyjziuvrisb.supabase.co/functions/v1/:splat"
  status = 200
  force = true
  headers = { Authorization = "Bearer YOUR_SUPABASE_ANON_KEY" }
