[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "https://irkfrlvddkyjziuvrisb.supabase.co/functions/v1/:splat"
  status = 200
  force = true
  headers = { Authorization = "Bearer YOUR_SUPABASE_ANON_KEY" }

# netlify.toml
[functions]
  node_bundler = "esbuild"
  external_node_modules = ["rss-parser"]

[[scheduled.functions]]
  name = "fetch_crc_news"
  cron = "0 * * * *"   # hourly
