[build]
  command = "npm run build"
  publish = "dist"

# Vite SPA configuration - no framework plugin needed

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["rss-parser", "nodemailer"]

# Environment variables for functions are set in Netlify Dashboard
# SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, OPENAI_API_KEY, etc.

# Route API calls to functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# SPA fallback - serve index.html for all routes not matching files or functions
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Scheduled function for fetching CRC news
[[scheduled.functions]]
  name = "fetch_crc_news"
  cron = "0 */2 * * *"   # every 2 hours
